version: "3.8"

services:
  node1:
    hostname: node1
    image: docker:dind
    environment:
      DOCKER_TLS_CERTDIR: /certs
    privileged: true
    volumes:
      -  ./certs:/certs
      - ./docker-daemon.json:/etc/docker/daemon.json
    ports:
      - "12376:2376"
  node2:
    hostname: node2
    image: docker:dind
    privileged: true
    volumes:
      - ./docker-daemon.json:/etc/docker/daemon.json
  node3:
    hostname: node3
    image: docker:dind
    privileged: true
    volumes:
      - ./docker-daemon.json:/etc/docker/daemon.json
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./registry-config.yml:/etc/docker/registry/config.yml
